version: "3"
services:
  mongo:
    image: mongo
    expose: 
      - 27017
  webapp:
    build: .
    ports: 
      - 3000:80
    environment: 
      MONGO_URL: mongodb://mongo:27017/simplechat
      ROOT_URL: http://localhost:3000

